export enum UserActionTypes {
  IS_LOGGED_IN = 'USER/IS_LOGGED_IN',
  SET_USER = 'USER/SET_USER',
  DEL_USER = 'USER/DEL_USER',
  SIGN_UP = 'USER/SIGN_UP',
  SIGN_IN = 'USER/SIGN_IN',
  SIGN_OUT = 'USER/LOGOUT'
}
