// Getters (GET*)
// [CONTEXT]_[ACTION]_[PROPERTY]
export const AUTH_IS_LOGGED = 'AUTH_IS_LOGGED';

// Mutations (SET*, ADD*, REMOVE*)
// [CONTEXT]_[ACTION]_[PROPERTY]
export const AUTH_SET_USER = 'AUTH_SET_USER';

// Actions (FETCH*, CREATE*, UPDATE*, DELETE*)
// [CONTEXT]_[ACTION]_[PROPERTY]_[STATUS]
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
